/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAL.Animal;
import javax.persistence.EntityManagerFactory;
import DAL.Consulta;
import DAL.Funcionario;
import DAL.Tipofuncionario;
import java.math.BigDecimal;
import java.math.BigInteger;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 35192
 */
public class AdicionaConsulta extends javax.swing.JPanel {

    private MenuPrincipal parentFrame;
    private static final String Persistence_UNIT_NAME = "1Projeto2PU";
    private static EntityManagerFactory factory;

    /**
     * Creates new form AdicionaConsulta
     */
    public AdicionaConsulta(MenuPrincipal parent) {
        initComponents();
        parentFrame = parent;
        setSize(1071, 750);
        addVeterinarios();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        idan = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Preco = new javax.swing.JTextField();
        data = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jPanel1HierarchyChanged(evt);
            }
        });
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(36, 64, 102));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 35)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VetAnimar");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(402, 402, 402)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1071, 83);

        jLabel5.setBackground(new java.awt.Color(36, 64, 102));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(36, 64, 102));
        jLabel5.setText("Adicionar Consulta");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(430, 120, 270, 30);

        jLabel6.setBackground(new java.awt.Color(36, 64, 102));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(36, 64, 102));
        jLabel6.setText("Nome do veterinário:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(240, 340, 160, 30);

        jButton1.setBackground(new java.awt.Color(36, 64, 102));
        jButton1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Adicionar Consulta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(680, 650, 230, 33);

        jButton2.setBackground(new java.awt.Color(36, 64, 102));
        jButton2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(930, 650, 115, 33);

        jLabel10.setBackground(new java.awt.Color(36, 64, 102));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(36, 64, 102));
        jLabel10.setText("Data:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(350, 260, 50, 20);

        idan.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        idan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idanActionPerformed(evt);
            }
        });
        jPanel1.add(idan);
        idan.setBounds(440, 300, 410, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Veterinário", "Lewie Pardy", "Corissa Bowditch", "Shae Wroth", "Arlen Albany", "Maribeth Kaaskooper", "Ardyth Wetheril", "Roxi Banister", "" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(440, 340, 160, 30);

        jLabel7.setBackground(new java.awt.Color(36, 64, 102));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(36, 64, 102));
        jLabel7.setText("Preco base:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(300, 220, 90, 20);

        Preco.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        Preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecoActionPerformed(evt);
            }
        });
        jPanel1.add(Preco);
        Preco.setBounds(440, 220, 410, 30);

        data.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataActionPerformed(evt);
            }
        });
        jPanel1.add(data);
        data.setBounds(440, 260, 410, 30);

        jLabel8.setBackground(new java.awt.Color(36, 64, 102));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(36, 64, 102));
        jLabel8.setText("Número do chip:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(270, 300, 120, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1071, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jPanel1HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1HierarchyChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void idanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idanActionPerformed

    }//GEN-LAST:event_idanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.parentFrame.trocaPainel(new GestaoConsultas(this.parentFrame));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String PrecoInput = Preco.getText();
        String dataInput = data.getText();
        String idanInput = idan.getText();
        
         boolean camposVazios = false;

        if (PrecoInput.isEmpty() || dataInput.isEmpty() || idanInput.isEmpty() ) {
            camposVazios = true;
        }

        if (camposVazios) {
            JOptionPane.showMessageDialog(null, "Preencher todos os campos obrigatórios!!!");
       
        } else {
            int input = JOptionPane.showOptionDialog(null, "Pretende adicionar consulta?", "Sucesso", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);

         if (input == JOptionPane.OK_OPTION) {
        factory = Persistence.createEntityManagerFactory(Persistence_UNIT_NAME);
        EntityManager em = factory.createEntityManager();
        Consulta consulta = new Consulta();
        consulta.setPrecobase(PrecoInput);
        consulta.setDatahoraconsulta(dataInput);
        Animal animal = findAnimal(new BigInteger(idanInput));
        consulta.setIdanimal(animal);
        consulta.setEstado("0");

       Funcionario funcionario = null;
        Query q = em.createNamedQuery("Funcionario.findAll");
        for (Object d : q.getResultList()) {
            if ((((Funcionario) d).getNome()).equals((String) jComboBox1.getSelectedItem())) {
                funcionario = (Funcionario) d;
            }
        }
        consulta.setIdfuncionario(funcionario);

        em.getTransaction().begin();
        em.persist(consulta);
        em.getTransaction().commit();
        
         this.parentFrame.trocaPainel(new GestaoConsultas(this.parentFrame));
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecoActionPerformed

    private void dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataActionPerformed
  private void addVeterinarios() {

        factory = Persistence.createEntityManagerFactory(Persistence_UNIT_NAME);
        EntityManager em = factory.createEntityManager();
        Query q = em.createNamedQuery("Funcionario.findAll");
        jComboBox1.removeAllItems();
        for (Object d : q.getResultList()) {
            if (((Funcionario) d).getCodtipofuncionario().getCodtipofuncionario().intValue() == 2) {
                jComboBox1.addItem(((Funcionario) d).getNome());
            }
        }

    }

    private Animal findAnimal(BigInteger numChip) {

        factory = Persistence.createEntityManagerFactory(Persistence_UNIT_NAME);
        EntityManager em = factory.createEntityManager();
        Query q = em.createNamedQuery("Animal.findAll");
        Animal animal = null;
        for (Object d : q.getResultList()) {
            if (((Animal) d).getNumchip().compareTo(numChip) == 0) {
                animal = (Animal) d;
            }
        }

        return animal;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Preco;
    private javax.swing.JTextField data;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextField idan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
