/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAL.Animal;
import DAL.Funcionario;
import java.math.BigDecimal;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import DAL.Consulta;
import java.math.BigInteger;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author 35192
 */
public class EditarConsulta extends javax.swing.JPanel {

    private MenuPrincipal parentFrame;
    private static final String Persistence_UNIT_NAME = "1Projeto2PU";
    private static EntityManagerFactory factory;
    private Consulta cons;

    public EditarConsulta(MenuPrincipal parent, BigDecimal idCons) {
        initComponents();
        parentFrame = parent;
        setSize(1071, 750);
        setCons(idCons);
        popularForm();
        addVeterinarios();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        idan = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        Preco = new javax.swing.JTextField();
        data = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jPanel7HierarchyChanged(evt);
            }
        });
        jPanel7.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(36, 64, 102));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 35)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("VetAnimar");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(387, 387, 387)
                .addComponent(jLabel11)
                .addContainerGap(453, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel8);
        jPanel8.setBounds(0, 0, 1071, 83);

        jLabel13.setBackground(new java.awt.Color(36, 64, 102));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(36, 64, 102));
        jLabel13.setText("Editar Consulta");
        jPanel7.add(jLabel13);
        jLabel13.setBounds(450, 150, 180, 30);

        jLabel14.setBackground(new java.awt.Color(36, 64, 102));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(36, 64, 102));
        jLabel14.setText("Nome do veterinário:");
        jPanel7.add(jLabel14);
        jLabel14.setBounds(290, 360, 160, 30);

        jButton1.setBackground(new java.awt.Color(36, 64, 102));
        jButton1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1);
        jButton1.setBounds(690, 680, 170, 33);

        jButton2.setBackground(new java.awt.Color(36, 64, 102));
        jButton2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2);
        jButton2.setBounds(880, 680, 115, 33);

        jLabel15.setBackground(new java.awt.Color(36, 64, 102));
        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(36, 64, 102));
        jLabel15.setText("Data:");
        jPanel7.add(jLabel15);
        jLabel15.setBounds(400, 280, 50, 20);

        idan.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        idan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idanActionPerformed(evt);
            }
        });
        jPanel7.add(idan);
        idan.setBounds(470, 320, 410, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Veterinário", "Lewie Pardy", "Corissa Bowditch", "Shae Wroth", "Arlen Albany", "Maribeth Kaaskooper", "Ardyth Wetheril", "Roxi Banister", "" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel7.add(jComboBox1);
        jComboBox1.setBounds(470, 360, 160, 30);

        jLabel16.setBackground(new java.awt.Color(36, 64, 102));
        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(36, 64, 102));
        jLabel16.setText("Preco base:");
        jPanel7.add(jLabel16);
        jLabel16.setBounds(350, 240, 90, 20);

        Preco.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        Preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecoActionPerformed(evt);
            }
        });
        jPanel7.add(Preco);
        Preco.setBounds(470, 240, 410, 30);

        data.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataActionPerformed(evt);
            }
        });
        jPanel7.add(data);
        data.setBounds(470, 280, 410, 30);

        jLabel17.setBackground(new java.awt.Color(36, 64, 102));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(36, 64, 102));
        jLabel17.setText("Número do chip:");
        jPanel7.add(jLabel17);
        jLabel17.setBounds(320, 320, 130, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1071, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        factory = Persistence.createEntityManagerFactory(Persistence_UNIT_NAME);
        EntityManager em = factory.createEntityManager();
        int input = JOptionPane.showOptionDialog(null, "Pretende guardar as alterações efetuadas?", "Sucesso", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);

        if (input == JOptionPane.OK_OPTION) {
            this.cons.setPrecobase(Preco.getText());
            this.cons.setDatahoraconsulta(data.getText());
            Animal animal = findAnimal(new BigInteger(idan.getText()));
            this.cons.setIdanimal(animal);

            Funcionario funcionario = null;
            Query q = em.createNamedQuery("Funcionario.findAll");
            for (Object d : q.getResultList()) {
                if ((((Funcionario) d).getNome()).equals((String) jComboBox1.getSelectedItem())) {
                    funcionario = (Funcionario) d;
                }
            }
            this.cons.setIdfuncionario(funcionario);

            em.getTransaction().begin();
            em.merge(this.cons);
            em.getTransaction().commit();

            this.parentFrame.trocaPainel(new GestaoConsultas(this.parentFrame));
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.parentFrame.trocaPainel(new GestaoConsultas(this.parentFrame));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void idanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idanActionPerformed

    }//GEN-LAST:event_idanActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void PrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecoActionPerformed

    private void dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataActionPerformed

    private void jPanel7HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jPanel7HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7HierarchyChanged
    private void addVeterinarios() {

        factory = Persistence.createEntityManagerFactory(Persistence_UNIT_NAME);
        EntityManager em = factory.createEntityManager();
        Query q = em.createNamedQuery("Funcionario.findAll");
        jComboBox1.removeAllItems();
        for (Object d : q.getResultList()) {
            if (((Funcionario) d).getCodtipofuncionario().getCodtipofuncionario().intValue() == 2) {
                jComboBox1.addItem(((Funcionario) d).getNome());
            }
        }

    }
    
    private void setCons(BigDecimal idCons) {
        
        
        factory = Persistence.createEntityManagerFactory(Persistence_UNIT_NAME);
        EntityManager em = factory.createEntityManager();
        Query q = em.createNamedQuery("Consulta.findAll");
        Consulta con = null;
        for (Object d : q.getResultList()) {
            BigDecimal id = ((Consulta) d).getIdconsulta();
            if (id.compareTo(idCons) == 0) {
                con = ((Consulta) d);
            }
        }
        this.cons = con;
    }

    private void popularForm() {

        Preco.setText(this.cons.getPrecobase());
        data.setText(this.cons.getDatahoraconsulta());
        idan.setText(this.cons.getIdanimal().getNumchip().toString());

        this.cons.getIdfuncionario();

        ComboBoxModel model = jComboBox1.getModel();
        int tamanho = model.getSize();
        int index = 0;
        for (int i = 0; i < tamanho; i++) {
            String nome = (String) model.getElementAt(i);
            if(nome.equals(this.cons.getIdfuncionario().getNome())){
                index = i;
            }
        }
        
        jComboBox1.setSelectedIndex(index);

    }

    private Animal findAnimal(BigInteger numChip) {

        factory = Persistence.createEntityManagerFactory(Persistence_UNIT_NAME);
        EntityManager em = factory.createEntityManager();
        Query q = em.createNamedQuery("Animal.findAll");
        Animal animal = null;
        for (Object d : q.getResultList()) {
            if (((Animal) d).getNumchip().compareTo(numChip) == 0) {
                animal = (Animal) d;
            }
        }

        return animal;

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Preco;
    private javax.swing.JTextField data;
    private javax.swing.JTextField idan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
