package GUI;

import DAL.Animal;
import DAL.Consulta;
import DAL.Especialidadefuncionario;
import static DAL.Especialidadefuncionario_.funcionario;
import DAL.Exame;
import static DAL.Exame_.especialidadefuncionario;
import DAL.Funcionario;
import DAL.Tipofuncionario;
import java.math.BigDecimal;
import java.math.BigInteger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 35192
 */
public class RegistarExame extends javax.swing.JPanel {

    private MenuPrincipal parentFrame;
    private static final String Persistence_UNIT_NAME = "1Projeto2PU";
    private static EntityManagerFactory factory;
    BigDecimal idConsulta = null;

    /**
     * Creates new form AdministrarUtilizadores
     */
    public RegistarExame(MenuPrincipal parent, BigDecimal idConsulta) {
        initComponents();
        parentFrame = parent;
        this.idConsulta = idConsulta;

        popularCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        nordem = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        des = new javax.swing.JTextField();
        preco = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        data = new javax.swing.JTextField();
        nchip = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(900, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jPanel1HierarchyChanged(evt);
            }
        });
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(36, 64, 102));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 35)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VetAnimar");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(374, 374, 374)
                .addComponent(jLabel2)
                .addContainerGap(466, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1071, 83);

        jLabel5.setBackground(new java.awt.Color(36, 64, 102));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(36, 64, 102));
        jLabel5.setText("Registo de Exame");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(420, 130, 250, 30);

        jButton1.setBackground(new java.awt.Color(36, 64, 102));
        jButton1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(750, 680, 115, 33);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(36, 64, 102));
        jLabel1.setText("Data do exame:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(460, 510, 160, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(36, 64, 102));
        jLabel4.setText("Número do chip:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(450, 260, 160, 20);

        jButton2.setBackground(new java.awt.Color(36, 64, 102));
        jButton2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(910, 680, 115, 33);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(36, 64, 102));
        jLabel6.setText("Número da ordem:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(450, 190, 160, 20);
        jPanel1.add(nordem);
        nordem.setBounds(400, 220, 250, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(36, 64, 102));
        jLabel8.setText("Descrição:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(470, 330, 160, 20);
        jPanel1.add(des);
        des.setBounds(400, 360, 250, 70);
        jPanel1.add(preco);
        preco.setBounds(400, 470, 250, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(36, 64, 102));
        jLabel10.setText("Preço do exame:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(460, 440, 160, 20);
        jPanel1.add(data);
        data.setBounds(400, 540, 250, 30);
        jPanel1.add(nchip);
        nchip.setBounds(400, 290, 250, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1071, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nordemInput = nordem.getText();
        String nchipInput = nchip.getText();
        String desInput = des.getText();
        String precoInput = preco.getText();
        String dataInput = data.getText();
        boolean camposVazios = false;

        if (nordemInput.isEmpty() || dataInput.isEmpty() || nchipInput.isEmpty() || desInput.isEmpty() || precoInput.isEmpty()) {
            camposVazios = true;
        }

        if (camposVazios) {
            JOptionPane.showMessageDialog(null, "Preencher todos os campos obrigatórios!!!");

        } else {
            int input = JOptionPane.showOptionDialog(null, "Pretende marcar exame?", "Sucesso", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);

            if (input == JOptionPane.OK_OPTION) {
                factory = Persistence.createEntityManagerFactory(Persistence_UNIT_NAME);
                EntityManager em = factory.createEntityManager();

                Exame exame = new Exame();
                Animal animal = findAnimal(new BigInteger(nchipInput));
                exame.setIdanimal(animal);
                exame.setIdfuncionario("" + findNordem(nordemInput));
                exame.setPrecoexame(precoInput);
                exame.setDescricaoexame(desInput);
                exame.setData(dataInput);
                exame.setEstado("0");

                em.getTransaction().begin();
                em.persist(exame);
                em.getTransaction().commit();

                this.parentFrame.trocaPainel(new AreaConsulta(this.parentFrame, idConsulta));

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.parentFrame.trocaPainel(new AreaConsulta(this.parentFrame, idConsulta));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPanel1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jPanel1HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1HierarchyChanged

    private Animal findAnimal(BigInteger numChip) {

        factory = Persistence.createEntityManagerFactory(Persistence_UNIT_NAME);
        EntityManager em = factory.createEntityManager();
        Query q = em.createNamedQuery("Animal.findAll");
        Animal animal = null;
        for (Object d : q.getResultList()) {
            if (((Animal) d).getNumchip().compareTo(numChip) == 0) {
                animal = (Animal) d;
            }
        }

        return animal;

    }

    private BigDecimal findNordem(String Numregisto) {
        factory = Persistence.createEntityManagerFactory(Persistence_UNIT_NAME);
        EntityManager em = factory.createEntityManager();
        Query q = em.createNamedQuery("Funcionario.findAll");
        BigDecimal id = null;
        for (Object d : q.getResultList()) {
            if (((Funcionario) d).getNumregisto() != null) {
                if (((Funcionario) d).getNumregisto().compareTo(new BigInteger(Numregisto)) == 0) {
                    id = ((Funcionario) d).getIdfuncionario();
                }

            }
        }

        return id;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField data;
    private javax.swing.JTextField des;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nchip;
    private javax.swing.JTextField nordem;
    private javax.swing.JTextField preco;
    // End of variables declaration//GEN-END:variables

    private void popularCampos() {
        factory = Persistence.createEntityManagerFactory(Persistence_UNIT_NAME);
        EntityManager em = factory.createEntityManager();
        
        Consulta consulta = em.find(Consulta.class, idConsulta);
        Animal animal = consulta.getIdanimal();
        Funcionario funcionario = consulta.getIdfuncionario();
        
        nordem.setText("" + funcionario.getNumregisto());
        nchip.setText("" + animal.getNumchip());
        
    }
}
