package GUI;

import DAL.Animal;
import DAL.Consulta;
import static DAL.Especialidadefuncionario_.exame;
import static DAL.Especialidadefuncionario_.funcionario;
import DAL.Exame;
import DAL.Funcionario;
import DAL.Medicamento;
import DAL.Receitamedica;
import DAL.Tipofuncionario;
import java.math.BigDecimal;
import java.math.BigInteger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 35192
 */
public class RegistarReceita extends javax.swing.JPanel {
    
    private MenuPrincipal parentFrame;
    private static final String Persistence_UNIT_NAME = "1Projeto2PU";
    private static EntityManagerFactory factory;
    BigDecimal idConsulta = null;

    /**
     * Creates new form AdministrarUtilizadores
     */
    public RegistarReceita(MenuPrincipal parent, BigDecimal idconsulta) {
        initComponents();
        parentFrame = parent;
        this.idConsulta = idconsulta;
        popularCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        validade = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        obs = new javax.swing.JTextArea();
        nordem = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        nchip1 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(900, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jPanel1HierarchyChanged(evt);
            }
        });
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(36, 64, 102));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 35)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VetAnimar");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(402, 402, 402)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1071, 83);

        jLabel5.setBackground(new java.awt.Color(36, 64, 102));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(36, 64, 102));
        jLabel5.setText("Registo de Receita Médica");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(390, 140, 310, 30);

        jButton1.setBackground(new java.awt.Color(36, 64, 102));
        jButton1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(750, 680, 115, 33);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(36, 64, 102));
        jLabel6.setText("Número da Ordem:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(470, 200, 160, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(36, 64, 102));
        jLabel8.setText("Validade:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(510, 520, 70, 20);
        jPanel1.add(validade);
        validade.setBounds(420, 550, 250, 30);

        jComboBox2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(36, 64, 102));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medicamento", "Diptron 100 mg/mL solução para unção punctiforme para cães", "FullPet Spray - Antiparasitário para cães e gatos", "Mastidina - Para bovinos", "equinos", "caprinos", "ovinos", "suínos e cães", "Program 70 mg - Para gatos", "Program 67", "8 mg - Para cães", "Acarene Spray - Para pombos", "papagaios e outros psitacídeos", "aves canoras e ornamentais e coelhos", "Effipro 2", "5 mg/ml - Para gatos e cães", "Activyl 100 mg solução para unção punctiforme para cães de porte muito pequeno", "Zoopan Coccimir 50g/15g/5g", "Effinol 50 mg Solução Spot-On para gatos", "Effipro 50 mg - Para gatos", "Effinol 2", "5 mg/ml solução para pulverização cutânea para cães e gatos", "Kawu 15% coleira antiparasitária para caes", "Kawu 15% coleira antiparasitária para gatos", "Frontline Combo Spot-On M 134 mg - Para cães 10 -20 Kg", "Frontline Combo Spot-On S 67 mg - Para cães 2-10 kg", "Frontline Combo Spot-On XL 402 mg - Para cães 40-60 Kg", "Frontline Combo Spot-On 50 mg - Para gatos e furões", "Frontline Spray 2", "5 mg/ml - Para gatos e cães", "Eliminall 134 mg - Solução para Unção Punctiforme para Cães", "Eliminall 50 mg - Solução para Unção Punctiforme para Gatos", "Frontline Tri-Act - Para cães 2-5 Kg", "Diptron 100 mg/mL solução para unção punctiforme para cães", "Piretron 715 mg/mL solução para unção punctiforme para cães", "Fleanil 50 mg - Para gatos", "Defendog - Para cães", "Effitix 268 mg/2400 mg - Para cães grandes", "Eliminall 2", "5 mg/mL - Solução para Pulverização Cutânea para Cães e Gatos", "Peritol - Para cães", "Fipon Spray 0", "5 g/250 ml - Para cães e gatos", "Effinol Solução Spot-On para cães", "" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(60, 230, 240, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(36, 64, 102));
        jLabel9.setText("Número do Chip:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(480, 280, 160, 20);

        obs.setColumns(20);
        obs.setRows(5);
        jScrollPane1.setViewportView(obs);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(360, 390, 380, 110);
        jPanel1.add(nordem);
        nordem.setBounds(420, 230, 250, 30);

        jButton2.setBackground(new java.awt.Color(36, 64, 102));
        jButton2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(910, 680, 115, 33);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(36, 64, 102));
        jLabel10.setText("Observações:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(490, 360, 160, 20);
        jPanel1.add(nchip1);
        nchip1.setBounds(420, 310, 250, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1071, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nordemInput = nordem.getText();
        String nchipInput = nchip1.getText();
        String obsInput = obs.getText();        
        String validadeInput = validade.getText();
        boolean camposVazios = false;
        
        if (nordemInput.isEmpty() || nchipInput.isEmpty() || obsInput.isEmpty()) {
            camposVazios = true;
        }
        
        if (camposVazios) {
            JOptionPane.showMessageDialog(null, "Preencher todos os campos obrigatórios!!!");
            
        } else {
            int input = JOptionPane.showOptionDialog(null, "Pretende registar receita?", "Sucesso", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
            
            if (input == JOptionPane.OK_OPTION) {
                factory = Persistence.createEntityManagerFactory(Persistence_UNIT_NAME);
                EntityManager em = factory.createEntityManager();
                
                Receitamedica receita = new Receitamedica();
                Animal animal = findAnimal(new BigInteger(nchipInput));
                receita.setIdanimal(animal);
                Funcionario funcionario = em.find(Funcionario.class, findNordem(nordemInput));
                receita.setIdfuncionario(funcionario);
                receita.setObservacoes(obsInput);
                receita.setValidade(validadeInput);
                
                Medicamento m;
                m = new Medicamento(new BigDecimal("" + jComboBox2.getSelectedIndex()));
                receita.setIdmedicamento(m);
                
                em.getTransaction().begin();
                em.persist(receita);
                em.getTransaction().commit();
                
                this.parentFrame.trocaPainel(new AreaConsulta(this.parentFrame, idConsulta));
                
            }
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.parentFrame.trocaPainel(new AreaConsulta(this.parentFrame, idConsulta));        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPanel1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jPanel1HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1HierarchyChanged

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed
    
    private Animal findAnimal(BigInteger numChip) {
        
        factory = Persistence.createEntityManagerFactory(Persistence_UNIT_NAME);
        EntityManager em = factory.createEntityManager();
        Query q = em.createNamedQuery("Animal.findAll");
        Animal animal = null;
        for (Object d : q.getResultList()) {
            if (((Animal) d).getNumchip().compareTo(numChip) == 0) {
                animal = (Animal) d;
            }
        }
        
        return animal;
        
    }
    
    private BigDecimal findNordem(String Numregisto) {
        factory = Persistence.createEntityManagerFactory(Persistence_UNIT_NAME);
        EntityManager em = factory.createEntityManager();
        Query q = em.createNamedQuery("Funcionario.findAll");
        BigDecimal id = null;
        for (Object d : q.getResultList()) {
            if (((Funcionario) d).getNumregisto() != null) {
                if (((Funcionario) d).getNumregisto().compareTo(new BigInteger(Numregisto)) == 0) {
                    id = ((Funcionario) d).getIdfuncionario();
                }
                
            }
        }
        
        return id;
    }

    // Variables declaration - do not modify                     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nchip1;
    private javax.swing.JTextField nordem;
    private javax.swing.JTextArea obs;
    private javax.swing.JTextField validade;
    // End of variables declaration//GEN-END:variables

    private void popularCampos() {
        factory = Persistence.createEntityManagerFactory(Persistence_UNIT_NAME);
        EntityManager em = factory.createEntityManager();
        Consulta consulta = em.find(Consulta.class, idConsulta);
        Animal animal = consulta.getIdanimal();
        Funcionario funcionario = consulta.getIdfuncionario();
        
        nordem.setText("" + funcionario.getNumregisto());
        nchip1.setText("" + animal.getNumchip());
    }
}
